import type { Metadata } from 'next';
import { Space_Mono, Albert_Sans } from 'next/font/google';
import './globals.css';

const spaceMono = Space_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${spaceMono.className} antialiased`}>{children}</body>
    </html>
  );
}
